heat_template_version: queens

parameters:
  flavor:
    description: param for flavor
    type: string
    default: cirros256
  param_size:
    description: param for volume size
    type: number
    default: 1

resources:
  first_instance:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: cirros-0.5.2x86_64-disk
  volume_1:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: param_size}